import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from "next/font/google"; // ganti dari Inter ke Poppins

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"], // tambahkan ini
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "LoopFlare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        {children}
      </body>
    </html>
  );
}